version: '3.8'

services:
  canopy-server:
    image: ghcr.io/pinecone-io/canopy:main
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - INDEX_NAME=${INDEX_NAME}
    ports:
      - "8000:8000"

  my-app:
    image: flaskapp:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_USER_ID=${SLACK_BOT_USER_ID}
      - CONVERSATION_HISTORY_PATH=${CONVERSATION_HISTORY_PATH}
      - SECRET_ARN=${SECRET_ARN}
    ports:
      - "3000:3000"
